name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_INTEGER_ENV: 42

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set Environment Variable
        run: echo "MY_INTEGER_ENV=${{ env.MY_INTEGER_ENV }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover

      - name: Run Python Script
        run: |
          source venv/bin/activate
          python main.py
        env:
          MY_INTEGER_ENV: ${{ env.MY_INTEGER_ENV }}
